const cards = [
    {
        title: 'Sniper',
        description: 'Tower with increased\nrange and damage\nbut decreased speed.',
        color: 0xfacc15,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.sniper,
    },
    {
        title: 'Power Plant',
        description: 'Generates Energy.',
        color: 0x60a5fa,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        popular: true,
        itemConfig: globalConfig.items.powerPlant,
    },
    {
        title: 'Hammer',
        description: 'Melee Tower\nAttacks enemies in\nclose range.',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.hammer,
    },
    {
        title: 'Habitat',
        description: 'Produces Villagers',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.habitat,
    },
    {
        title: '+Production',
        description: 'Production\nMultiplier\nx2',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.productionMultiplier,
    },
    {
        title: '+Freeze',
        description: 'Tower has a\nchance to freeze\nenemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
    // TODO: below are dummies, remove
    {
        title: 'A',
        description: 'Tower has a\nchance to freeze\nenemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
    {
        title: 'B',
        description: 'Tower has a\nchance to freeze\nenemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
    {
        title: 'C',
        description: 'Tower has a\nchance to freeze\nenemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
    {
        title: 'D',
        description: 'Tower has a\nchance to freeze\nenemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
];