const cards = [
    {
        title: 'Sniper',
        description: 'Tower with increased range and damage but decreased speed.',
        color: 0xfacc15,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.sniper,
    },
    {
        title: 'Power Plant',
        description: 'Generates Energy.',
        color: 0x60a5fa,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        popular: true,
        itemConfig: globalConfig.items.powerPlant,
    },
    {
        title: 'Hammer',
        description: 'Melee Tower, attacks enemies in close range.',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.hammer,
    },
    {
        title: 'Habitat',
        description: 'Produces Villagers',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.habitat,
    },
    {
        title: '+Production',
        description: 'Production Multiplier x2',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.productionMultiplier,
    },
    {
        title: '+Freeze',
        description: 'Tower has a chance to freeze enemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
    // TODO: below are dummies, remove
    {
        title: 'A',
        description: 'Tower has a chance to freeze enemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
    {
        title: 'B',
        description: 'Tower has a chance to freeze enemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
    {
        title: 'C',
        description: 'Tower has a chance to freeze enemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
    {
        title: 'D',
        description: 'Tower has a chance to freeze enemies',
        color: 0x818cf8,
        costResourceRegistryKey: globalConfig.resources.token.registryKey,
        cost: 5,
        itemConfig: globalConfig.items.freeze,
    },
];